stages:
  - check
  - test
  - build

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:                         &default-vars
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CARGO_INCREMENTAL:               0
  ARCH:                            "x86_64"
  CI_IMAGE:                        "paritytech/ci-linux:production"

default:
  cache:                           {}

.collect-artifacts:                &collect-artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     7 days
    paths:
      - artifacts/

.kubernetes-build:                 &kubernetes-build
  tags:
    - kubernetes-parity-build
  interruptible:                   true

.docker-env:                       &docker-env
  image:                           "${CI_IMAGE}"
  before_script:
    - rustup show
    - cargo --version
    - sccache -s
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - linux-docker

#### stage:                        check

check-std:
  stage:                           check
  <<:                              *docker-env
  script:
    - echo "cargo check --verbose --all-features"

check-wasm:
  stage:                           check
  <<:                              *docker-env
  script:
    - echo "cargo check --verbose --no-default-features --target wasm32-unknown-unknown"

#### stage:                        workspace

build-std:
  stage:                           test
  <<:                              *docker-env
  needs:
    - job:                         check-std
      artifacts:                   false
  script:
    - echo "cargo build --verbose --all-features --release"

build-wasm:
  stage:                           test
  <<:                              *docker-env
  needs:
    - job:                         check-wasm
      artifacts:                   false
  script:
    - echo "cargo build --verbose --no-default-features --release --target wasm32-unknown-unknown"
    # debug