[workspace]

members = [
    "bin/node/node",
    "bin/node/runtime",
    "modules/ethereum",
    "modules/ethereum2",
	"modules/headerchain",
    "modules/substrate",
    "relays/ethereum",
    "relays/substrate",
]
