version: '3.5'
services:
  relay-eth2sub:
    image: paritytech/ethereum-poa-relay
    entrypoint: /config/relay-eth2sub-entrypoint.sh
    volumes:
      - ./bridge-config:/config
    environment:
      RUST_LOG: rpc=trace,bridge=trace
    ports:
      - "9616:9616"
    depends_on: &all-nodes
      - poa-node-arthur
      - poa-node-bertha
      - poa-node-carlos
      - bridge-node-alice
      - bridge-node-bob
      - bridge-node-charlie
      - bridge-node-dave
      - bridge-node-eve

  prometheus-metrics:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./dashboard/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    depends_on: *all-nodes

  grafana-dashboard:
    image: grafana/grafana:7.1.3
    environment:
      VIRTUAL_HOST: dashboard.rialto.bridges.test-installations.parity.io,grafana.rialto.brucke.link
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: dashboard.rialto.bridges.test-installations.parity.io,grafana.rialto.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS:-admin}
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT_URL}
      GF_SERVER_DOMAIN: ${GRAFANA_SERVER_DOMAIN}
    volumes:
      - ./dashboard/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-metrics
