# This Compose file should be built using the Rialto and Eth-PoA node
# compose files. Otherwise it won't work.
# ```
# $ docker-compose \
#   -f ./networks/rialto.yml \
#   -f ./networks/eth-poa.yml \
#   -f ./monitoring/docker-compose.yml \
#   -f ./bridges/rialto-poa/docker-compose.yml
# ```
# TODO Probably all the paths should be made relative to `./deployments` directory, so that
# we run from `./deploments` as CWD.

version: '3.5'
services:
  # We provide an override for this particular node since this is a public facing
  # node which we use to connect from things like Polkadot JS Apps.
  # TODO: Check that this override is done correctly (check order of -f files)
  rialto-node-charlie:
    environment:
      VIRTUAL_HOST: rialto.bridges.test-installations.parity.io,wss.rialto.brucke.link
      VIRTUAL_PORT: 9944
      LETSENCRYPT_HOST: rialto.bridges.test-installations.parity.io,wss.rialto.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io

  # RELAYERS
  relay-eth2sub:
    image: paritytech/ethereum-poa-relay
    entrypoint: /config/relay-eth2sub-entrypoint.sh
    volumes: &relay-config
      - ./relayers:/config
    environment: &relay-logs
      RUST_LOG: rpc=trace,bridge=trace
    ports:
      - "9616:9616"
    depends_on: &all-nodes
      - poa-node-arthur
      - poa-node-bertha
      - poa-node-carlos
      - rialto-node-alice
      - rialto-node-bob
      - rialto-node-charlie
      - rialto-node-dave
      - rialto-node-eve

  relay-eth-exchange-sub:
    image: paritytech/ethereum-poa-relay
    entrypoint: /config/relay-eth-exchange-sub-entrypoint.sh
    volumes: *relay-config
    environment: *relay-logs
    ports:
      - "9716:9616"
    depends_on: *all-nodes

  relay-sub2eth:
    image: paritytech/ethereum-poa-relay
    entrypoint: /config/relay-sub2eth-entrypoint.sh
    volumes: *relay-config
    environment: *relay-logs
    ports:
      - "9618:9616"
    depends_on: *all-nodes

  # GENERATORS
  poa-exchange-tx-generator:
    image: paritytech/ethereum-poa-relay
    entrypoint: /config/poa-exchange-tx-generator-entrypoint.sh
    volumes: *relay-config
    environment:
      <<: *relay-logs
      EXCHANGE_GEN_MIN_AMOUNT_FINNEY: ${EXCHANGE_GEN_MIN_AMOUNT_FINNEY:-1}
      EXCHANGE_GEN_MAX_AMOUNT_FINNEY: ${EXCHANGE_GEN_MAX_AMOUNT_FINNEY:-100000}
      EXCHANGE_GEN_MAX_SUBMIT_DELAY_S: ${EXCHANGE_GEN_MAX_SUBMIT_DELAY_S:-60}
    depends_on: *all-nodes

  # CURRENCY EXCHANGE UI
  front-end:
    build:
      context: .
      dockerfile: ./Front-end.Dockerfile
      args:
        SUBSTRATE_PROVIDER: ${UI_SUBSTRATE_PROVIDER:-ws://localhost:9944}
        ETHEREUM_PROVIDER: ${UI_ETHEREUM_PROVIDER:-http://localhost:8545}
        EXPECTED_ETHEREUM_NETWORK_ID: ${UI_EXPECTED_ETHEREUM_NETWORK_ID:-105}
    ports:
      - "8080:80"

  # METRICS & MONITORING
  prometheus-metrics:
    volumes:
      - ./dashboard/prometheus/:/etc/prometheus/
    depends_on: *all-nodes
  grafana-dashboard:
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      VIRTUAL_HOST: dashboard.rialto.bridges.test-installations.parity.io,grafana.rialto.brucke.link
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: dashboard.rialto.bridges.test-installations.parity.io,grafana.rialto.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io


